# install a usable base system.
# disable if you already have a "common" role for your environment

- name: handling apt.conf
  template: src=apt.conf dest=/etc/apt/apt.conf

- name: setting repos
  template: src=sources.list dest=/etc/apt/sources.list

- name: updating all packages
  apt: update_cache=yes cache_valid_time=3600

- name: install "base" packages
  apt: name={{ item }} state=present 
  with_items:
  - git
  - ntpdate

- name: pull CTFd from repo
  git: repo="{{ ctfd_git_repo }}"
       dest="{{ ctfd_base }}"
    
- debug: msg={{ ctfd_user }} 
    
- name: change ownershiop of CTFd directroy
  file: path={{ ctfd_base }} recurse=true owner={{ ctfd_user }} 
  
  
