# install a usable base system.
# disable if you already have a "common" role for your environment

#~ - name: check for aptproxy availability
  #~ command: ping -c 1 "{{ aptproxyserver }}"
  #~ register: ping_aptproxy
  #~ changed_when: false
  #~ failed_when: false
  #~ always_run: yes
#~ 
#~ - name: creating aptproxy boolean
  #~ set_fact: aptproxy_available={{ping_aptproxy.rc == 0}} 
#~ 
#~ - name: handling apt.conf
  #~ template: src=apt.conf dest=/etc/apt/apt.conf
  
- name: setting repos
  template: src=sources.list dest=/etc/apt/sources.list

- name: updating all packages
  apt: update_cache=yes cache_valid_time=3600

- name: install "base" packages
  apt: name={{ item }} state=present 
  with_items:
  - git
  - ntpdate

- name: Set user default password
  user: name={{ ctf_user }} password={{ ctf_user_pass }}

- name: Set root user default password
  user: name=root password={{root_pass}}
