# install files and other userspace config for use with the services.
- debug: msg="ctfc-userspace"

- name: create ctf directory
  file: path={{ctfc_base}} state=directory

# - name: copy utility scripts
#   copy: src={{item.src}} dest={{item.dest}}
#   with_items:
#   - { src: "{{ local_ctfd_dir }}/scripts/flag_deliver",  dest: "{{ ansible_env.HOME}}" }

- name: copy deliver_flag script
  copy:
    src: "{{ local_ctfd_dir }}/scripts/flag_deliver"
    dest: "{{ ansible_env.HOME}}"

# bashtard
#~ - name: create destination directories
  #~ file: path={{ item.dest_path }} state=directory recurse=yes
  #~ with_items: "{{ services_enabled }}"
  #~ tags: services
#~
#~ - name: include services
  #~ copy: src={{item.src_path}}/{{ item.filename }} dest={{item.dest_path}}/{{ item.filename }}
  #~ with_items: "{{ services_enabled }}"
  #~ tags: services
