# tasks to be run on the ansible machine

  - name: create temp directory
    file: path={{ local_temp_dir }} state=directory
    connection: local

  - name: pull CTFd locally
    connection: local
    git: repo="{{ ctfd_git_repo }}"
         dest="{{ local_ctfd_dir }}"
    
