# system tasks for the game clients
- debug: msg="ctfc-system"

- name: include services
  include: services/gameservices.yml
#~
#~ - name: install packages need by services
  #~ apt: name={{ item }} state=present
  #~ with_items:
  #~ - xinetd
#~
#~ - name: add xinetd services
  #~ template: src=xinetd-services.j2 dest=/etc/xinetd.d/{{item.name}}
  #~ with_items: "{{ services_enabled }}"
  #~ tags: services
  #~ notify: restart xinetd
#~
#~ - name: update services list
  #~ lineinfile:
    #~ dest=/etc/services
    #~ line="{{ item.name }}   {{ item.port }}/tcp"
    #~ state=present
    #~ insertafter=EOF
  #~ with_items: "{{ services_enabled }}"
  #~ tags: services
  #~ notify: restart xinetd
