# install relevant packages and configure ctfd

- name: create local config dir
  file: path={{ ctfd_local }} state=directory mode=0755

- name: create config file
  template: src=config.js.j2 dest="{{ ctfd_local }}/config.js"

- name: update npm
  shell: npm update >> npmupdate.log
  args:
    chdir: "{{ ctfd_base }}"
