# sets up the base systme.
# the server will run as its own user

- name: include extra vars
  include_vars: "{{ item }}"
  with_items:
  - defaults/services.yml
  tags: always

- include: users.yml
  become: yes
  tags: system

- include: install_packages.yml
  become: yes
  tags: system

- include: install_ctfd.yml
  when: include_ctfd

- include: install_ctfc.yml
  when: include_ctfc
