# sets up the base systme.
# the server will run as its own user

- name: include basesystem
  include: basesystem.yml
  when: include_basesystem
  become: yes

- name: include ctfd system part
  include: ctfd-system.yml
  become: yes

- name: include ctfd userspace part
  include: userspace.yml
  tags: userspace
