# sets up the base systme.
# the server will run as its own user

- name: include extra vars
  include_vars: "{{ item }}"
  with_items:
  - defaults/services.yml
  tags: always

- include: users.yml
  become: yes
  tags: system

- include: install_packages.yml
  become: yes
  tags: system

- block:
  - debug: msg="install ctf client and server - system"

  - include: ctfd-system.yml
    when: include_ctfd

  - include: ctfc-system.yml
    when: include_ctfc
  become: yes
  tags: system

- name: include ctfc local part
  include: ctfc-local.yml
  when: include_ctfd
  become: no

- block:
  - debug: msg="install ctf client and server - userspace"

  - include: ctfd-userspace.yml
    when: include_ctfd

  - include: ctfc-userspace.yml
    when: include_ctfc
  become_user: "{{ ctf_user }}"
  become: no
  tags: userspace
