# sets up the base systme.
# the server will run as its own user

- name: include extra vars
  include_vars: "{{ item }}"
  with_items:
  - defaults/services.yml
  tags: always

- name: include basesystem
  include: users.yml
  become: yes
  tags: system

- include: install_packages.yml
  become: yes
  tags: system

- name: include ctfd system part
  include: ctfd-system.yml
  when: include_ctfd
  become: yes
  tags: system

- name: include ctfd userspace part
  include: userspace.yml
  when: include_ctfd
  tags: userspace

- name: include ctfc system part
  include: ctfc-system.yml
  when: include_ctfc
  become: yes
  tags: system

- name: include ctfc local part
  include: ctfc-local.yml
  become: no
  when: include_ctfc

- name: include ctfc userspace part
  include: ctfc-userspace.yml
  when: include_ctfc
  become: no
  tags: userspace
