# sets up the base systme.
# the server will run as its own user

- name: include extra vars
  include_vars: "{{ item }}"
  with_items:
  - defaults/services.yml


- name: include basesystem
  include: basesystem.yml
  when: include_basesystem
  become: yes
  tags: basesystem

- name: include ctfd system part
  include: ctfd-system.yml
  when: include_ctfd
  become: yes

- name: include ctfd userspace part
  include: userspace.yml
  when: include_ctfd
  tags: userspace

- name: include ctfc system part
  include: ctfc-system.yml
  when: include_ctfc
  become: yes
  
- name: include ctfc local part
  include: ctfc-local.yml
  become: no
  when: include_ctfc
  
- name: include ctfc userspace part
  include: ctfc-userspace.yml
  when: include_ctfc
  tags: userspace

- name: include tests
  include: tests.yml
  when: run_tests
  tags: tests
  
