# install a usable base system.
# disable if you already have a "common" role for your environment



- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - git
  - ntpdate
  - ca-certificates

- name: Set user default password
  user: name={{ ctf_user }} password={{ ctf_user_pass }}

- name: Set root user default password
  user: name=root password={{root_pass}}
