- name: restart xinetd
  service: name=xinetd state=restarted
  become: yes

- name: restart apache
  service: name=apache2 state=restarted
  become: yes

- name: restart rc.local
  service: name=rc.local state=restarted 
  become: yes
