# bashtard

- name: install packages
  apt: name={{item}} state=present
  with_items:
  - xinetd

- name: copy files
  copy: src="{{local_ctfd_dir}}/services/Bashtard/src/" dest="{{ctfc_service_dir}}/Bashtard"

- name: add xinetd services
  template: src=xinetd-services.j2 dest=/etc/xinetd.d/{{item.name}}
  with_items: 
  - "{{ Bashtard }}"
  tags: services
  notify: restart xinetd

- name: update services list
  lineinfile:
    dest=/etc/services
    line="{{ item.name }}   {{ item.port }}/tcp"
    state=present
    insertafter=EOF
  with_items: 
  - "{{ Bashtard }}"
  tags: services
  notify: restart xinetd

