
# comman config
- name: include apache config
  include: apache.yml
  when: RabbitShare.enable

- name: install rc.local
  template: src=rc.local.j2 dest=/etc/rc.local
            mode=755 owner=root group=root
  notify: run rc.local
  when: PythonOnPills.enable


# services
- name: include bashtard
  include: bashtard.yml
  when: Bashtard.enable

- name: include RabbitShare
  include: rabbitshare.yml
  when: RabbitShare.enable

- name: include TicTacToe
  include: tictactoe.yml
  when: TicTacToe.enable

- name: include PythonOnPills
  include: pythononpills.yml
  when: PythonOnPills.enable
